packages:
  - symbols
  - www

savePrefix: ''

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  vue-demi: false

catalog:
  '@types/node': 26.0.0
  'typescript': 6.0.3
  vite-plus: 0.2.1
  vue: 3.5.38

overrides:
  vite: 'npm:@voidzero-dev/vite-plus-core@latest'
